# Generated by Django 5.1.1 on 2024-10-04 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('cr_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Currencies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cur_id', models.TextField()),
                ('cur_name', models.TextField()),
                ('cr_date', models.DateTimeField(auto_now_add=True)),
                ('cr_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pages.users')),
            ],
        ),
    ]
