# Generated by Django 5.1.1 on 2024-10-07 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_currencies_cus_sign'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currencies',
            old_name='cus_sign',
            new_name='cur_sign',
        ),
    ]
