# Generated by Django 5.1.1 on 2024-10-07 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_rename_cus_sign_currencies_cur_sign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currencies',
            name='cr_user',
        ),
    ]
