# Generated by Django 5.1.2 on 2024-10-14 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_remove_currencies_cr_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencySign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cur_sign', models.CharField()),
                ('sign', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cur_desc', models.CharField()),
                ('cur_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cur_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pages.currencies')),
            ],
        ),
        migrations.AlterField(
            model_name='currencies',
            name='cur_sign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pages.currencysign'),
        ),
    ]
