# Generated by Django 5.1.2 on 2024-10-15 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_currencysign_currencyprice_alter_currencies_cur_sign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currencyprice',
            name='cur_id',
        ),
        migrations.AddField(
            model_name='currencies',
            name='cur_desc',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='currencies',
            name='cur_price',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pages.currencyprice'),
        ),
    ]
