# Generated by Django 5.1.1 on 2024-10-19 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_currencies_dtl_remove_currencies_cur_price_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Currencies_dtl',
            new_name='Tags',
        ),
    ]
