# Generated by Django 5.1.1 on 2024-10-19 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_rename_currencies_dtl_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags',
            name='cr_date',
        ),
    ]
