# Generated by Django 5.1.1 on 2024-10-19 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_remove_tags_cr_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currencies',
            name='cur_dtl',
        ),
    ]
