# Generated by Django 5.1.1 on 2024-10-20 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_currencies_cur_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currencies',
            old_name='cur_tags',
            new_name='cur_tag',
        ),
    ]
