# Generated by Django 5.1.1 on 2024-10-20 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_rename_cur_tags_currencies_cur_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curr_Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cur_id', models.TextField()),
                ('tag_id', models.TextField()),
            ],
        ),
    ]
