# Generated by Django 5.1.1 on 2024-10-22 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TaskType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_desc', models.CharField()),
                ('job_date', models.DateField()),
                ('taskjob', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tasks.taskjob')),
                ('tasktype', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tasks.tasktype')),
            ],
        ),
    ]
