# Generated by Django 5.1.1 on 2024-10-23 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_taskjob_jobname_tasks_taskdesc_tasktype_typename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='jobdate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
