# Generated by Django 5.1.1 on 2024-10-23 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_tasks_jobdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='jobdate',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
