# Generated by Django 5.1.1 on 2024-10-25 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_company_tasks_amount_tasks_fromtime_tasks_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='comp_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tasks.company'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='jobdate',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='taskdesc',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='taskjob',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tasks.taskjob'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='tasktype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tasks.tasktype'),
        ),
    ]
