# Generated by Django 5.1.1 on 2024-10-25 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_tasks_comp_id_alter_tasks_jobdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='jobdate',
            field=models.DateField(auto_now=True),
        ),
    ]
