# Generated by Django 5.1.1 on 2024-10-25 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_tasks_jobdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='jobdate',
            field=models.DateField(),
        ),
    ]
