# Generated by Django 5.1.1 on 2024-10-25 13:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_company_cr_date_taskjob_cr_date_tasks_cr_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='taskdate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
