# Generated by Django 5.1.1 on 2024-10-25 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_alter_tasks_taskdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='taskdate',
        ),
    ]
