# Generated by Django 5.1.1 on 2024-10-25 14:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_remove_tasks_taskdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='taskdate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
