# Generated by Django 5.1.1 on 2024-10-28 20:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_alter_tasks_taskdate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='upd_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='taskjob',
            name='upd_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tasks',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Confirmed'), (3, 'Canceled')], default=1),
        ),
        migrations.AddField(
            model_name='tasks',
            name='upd_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tasks',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasktype',
            name='upd_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
